### ISSUE TITLE
Can't get the ussd return

### ISSUE THREAD

**Issue by StrongDevR** [lucdotdev/hover_ussd#5]
Hey,

I took over this repository (V 2.0), 

but I cannot recover the result of the USSD request on the interface of the application. The request is well done, the result is displayed on the Hover interface but can't get the result in the main interface of app. 

How to get the response of the session?

Is'it possible to desable SMS listening ?

**Comment by lucdotdev** [comment]
the v 2.0 are currently in WIP , many of you notice that issues , I plan to look more deeper on that soon,
for the sms listening , i plan to make another plugin without sms listening , something like hover_ussd_no_sms.

**Comment by StrongDevR** [comment]
Ok I can't wait for your return.

without SMS would be interesting. SMS listening permissions are sensitive and Google Play does not easily validate applications with SMS listening.

Especially since in this case, the USSD returns are sufficient to make the application work.

**Comment by lucdotdev** [comment]
Fixed in the latest version

**Comment by mapay** [comment]
Dear
I still cannot recover the result of the request. This time I get this : 

Ussd failed message: 
{errorMessage: null}

this return is displayed as soon as the ussd request is launched without waiting for the end of the request

**Comment by StrongDevR** [comment]
Dear
I still cannot recover the result of the request. This time I get this :

Ussd failed message:
{errorMessage: null}

this return is displayed as soon as the ussd request is launched without waiting for the end of the requ

**Comment by StrongDevR** [comment]
@lucdotdev On my dashboard Hover the action still pending. But successfully executed on my phone. The response is display on the Hover screen but the app can't get it.

**Comment by StrongDevR** [comment]
I would like to specify anyway that Hover retrieves all the results of the different USSD sessions. But the problem is in the recovery of the result of the last session.

**Comment by muhammed-amein** [comment]
@StrongDevR, The useHover status is pending because you didn't parse the result if it is success or not, cuz the SDK won't recognize each response success or pending unless you specify what is right and what's wrong.

**Comment by muhammed-amein** [comment]
waad mahadsantahay madhahaysidoo
